# $Id: Makefile 13 2009-11-26 16:37:03Z maf $

INSTALL=install -c -m0755

BINS = otpdb2sc users2otpdb

BINDIR=/usr/local/ootp/bin

install:
	mkdir -p ${BINDIR}
	${INSTALL} ${BINS} ${BINDIR}
	@echo files installed in ${BINDIR}

